# +----------------------------------------------------------------------------------------------+ #
# |     Source Code:     https://github.com/MCDaddyTalk/SetHDB                                   | #
# |     Bug Reports:     https://github.com/McDaddytalk/SetHDB/issues                            | #
# |     Wiki (Docs):     https://github.com/McDaddyTalk/SetHDB/wiki                              | #
# |     Discord Support: https://discord.gg/<adddiscord>                                         | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #

# Modifying this will cause this file to break and regenerate.
config-Version: 8

# Currently, the available language translations are: English.
# If you would like to contribute to a language translation please create a pull request; https://github.com/McDaddyTalk/SetHDB/tree/master/files/locales
Language: 'English'

# General maintenance settings that do not affect functionality.
General:
  CheckforUpdates: true
  MetricsLogging: true
  Log-Commands: true
  Debugging: false

# Optional settings for MySQL database connections (default is flatfile).
Database:
  MySQL: false
  host: 'localhost'
  port: 3306
  table: 'database_name'
  user: 'root'
  pass: 'password'